View specs
Naledi-Dikgale/blog-app pull request #12
Opened 2023-07-24 13:30 UTC by Naledi-Dikgale

### In this PR we did the following

- [ ] Used Capybara to write integration tests for each view in my project.
```
- User index page
- user show page
- User post index page
- Post show page
```

- [ ] Made sure that the N+1 problem is solved when fetching all posts and their comments for a user.

- screenshot before fixing n+1

![beforen+1](https://github.com/Naledi-Dikgale/blog-app/assets/117156742/1144f9ef-9dad-49fc-b49d-7362882f20c5)

- screenshot after fixing n+1

![Aftern+1](https://github.com/Naledi-Dikgale/blog-app/assets/117156742/2e4c1f86-dc35-4188-9ffc-407410535026)

2023-07-24 14:16 UTC, abdulhamiid requested changes
Hi @Naledi-Dikgale 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that does not have a significant contribution from  partner(s)

- [ ] This milestone is a [pair-programming activity](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md#work-and-submission-mode).

- [ ] Please ensure that everyone has contributed equally to the project you're reviewing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-24 15:48 UTC, OyePriscilla requested changes
Hi @Naledi-Dikgale and @lugard1 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Used Capybara to write integration tests ✔️ 
Had featured tests for `Post index` page ✔️ 
Had featured tests for` Post show` page ✔️ 
Had featured tests for `User index` page ✔️ 
Had featured tests for `User show` page ❎ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-24 15:48 UTC, OyePriscilla commented on spec/views/users/users_index_spec.rb
> +  end
- [ ] The tests written in this file suppose to be for `users show` page according to the file name I think, the `url` added is pointing at the` post homepage` not `users show' page`. 👍 
- [ ] Kindly implement all the tests for user_show page as indicated in the requirement. 👍

2023-07-24 15:48 UTC, OyePriscilla commented on spec/views/users/users_show_spec.rb
> +
- [ ] If we go by the content of this file, I think it the file name should be `users_index_spec.rb` not `users_show_spec.rb`. 👍 
- [ ] Please kindly add the missing test as well. ℹ️ 

<img width="402" alt="Untitled" src="https://github.com/Naledi-Dikgale/blog-app/assets/103386183/38ab17e0-9f2d-47f3-8968-1b0d66d5bee5">

2023-07-24 15:48 UTC, OyePriscilla commented on spec/views/posts/posts_index_spec.rb
> +    end
- [ ] Please kindly add the following missing tests as well in accordanc to the project requirement. ℹ️

<img width="567" alt="Untitled" src="https://github.com/Naledi-Dikgale/blog-app/assets/103386183/62fcb239-7d52-4648-97e0-d7e2ec54b398">

2023-07-25 05:57 UTC, Ismailco requested changes
### Hi @Naledi-Dikgale, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 05:57 UTC, Ismailco commented on spec/views/users/users_show_spec.rb
> +
- [ ] [OPTIONAL] Kindly make sure to implement tests that assert you can see a button that lets me view all of a user's posts.

2023-07-25 05:57 UTC, Ismailco commented on spec/views/users/users_index_spec.rb
> +
- [ ] This is a test for the `Posts` index page as the previous reviewer mentioned kindly consider moving these tests to the `posts_index_spec.rb` file instead

2023-07-25 05:57 UTC, Ismailco commented on spec/views/posts/posts_index_spec.rb
- [ ] These tests are the same as the ones you created in the `users_index_spec.rb` kindly make sure to not repeat the same tests in different files, instead you should keep these tests and modify the `users_index_spec.rb` to test the `Users` index page

2023-07-25 05:57 UTC, Ismailco commented on spec/views/users/users_index_spec.rb
> +
- [ ] As the previous reviewer suggested kindly consider adding tests for the `User` index page by modifying these files and removing unrelated tests. here are the required tests for the user index page 👇🏼. You can see is the before method on line 10 you're visiting the posts index page instead ` visit "/users/#{@user.id}/posts"`, it should be   `visit "/users"`

![](https://user-images.githubusercontent.com/103386183/255639827-38ab17e0-9f2d-47f3-8968-1b0d66d5bee5.png)

2023-07-25 12:38 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Naledi-Dikgale and @lugard1,

✔️ Well-written and passing tests

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 14:17 UTC, merged